version: "3.9"

services:
  app:
    build: .
    container_name: pulsecheck_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
      - rabbitmq
    volumes:
      - .:/app
    networks:
      - pulsecheck_net
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    container_name: pulsecheck_worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongo
    volumes:
      - .:/app
    networks:
      - pulsecheck_net
    command: /app/wait-for-it.sh rabbitmq 5672 -- python -m app.workers.worker

  postgres:
    image: postgres:16
    container_name: pulsecheck_postgres
    restart: always
    environment:
      POSTGRES_USER: pulseuser
      POSTGRES_PASSWORD: pulsepass
      POSTGRES_DB: pulsecheckdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pulsecheck_net

  mongo:
    image: mongo:7
    container_name: pulsecheck_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pulsecheck_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pulsecheck_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" # UI web no localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - pulsecheck_net

volumes:
  postgres_data:
  mongo_data:

networks:
  pulsecheck_net:
    driver: bridge
